# Generated by Django 5.1.1 on 2024-11-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quiz_youtube_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='quiz',
            name='creator_id',
            field=models.IntegerField(null=True),
        ),
    ]
